language: python
python:
  - "2.7"
  - "2.6"
env:
 - DJANGO=1.4
 - DJANGO=1.5
install:
 - pip install -q Django==$DJANGO --use-mirrors
 - pip install -r requirements.txt --use-mirrors
before_script:
 - python django_project/first_time_init.py
 - python manage.py syncdb --noinput
script:
 - coverage run manage.py test chpasswd
after_success:
 - coveralls
